# Generated by Django 2.2 on 2020-05-01 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='imagefun',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
